#!/usr/bin/env bash
# Displays PIDs for processes containing "bash"
# shellcheck disable=SC2009

for pid in $(ls /proc | grep '^[0-9]\+$'); do
    if [ -r "/proc/$pid/comm" ]; then
        name=$(<"/proc/$pid/comm")
        if echo "$name" | grep -iq "bash"; then
            echo "$pid $name"
        fi
    fi
done
