#!/usr/bin/env bash
# Display bash-related PIDs in format: PID process_name
# shellcheck disable=SC2009

for pid in /proc/[0-9]*; do
    comm="$pid/comm"
    if [ -r "$comm" ]; then
        read -r name < "$comm"
        if [[ "$name" =~ ^-?bash$ ]]; then
            echo "${pid##*/} $name"
        fi
    fi
done

