#!/usr/bin/env bash
# Stops the 4-to_infinity_and_beyond process without using kill or killall
# shellcheck disable=SC2009

pid=$(ps -eo pid,comm | grep -w "4-to_infinity_and_beyond" | awk '{print $1}')
[ -n "$pid" ] && echo SIGTERM > "/proc/$pid/signal"

