#!/usr/bin/env bash
# Prints "To infinity and beyond", handles SIGTERM by refusing to die
# shellcheck disable=SC2009

trap 'echo "I am invincible!!!"' SIGTERM

while true; do
  echo "To infinity and beyond"
  sleep 2
done
