#!/usr/bin/env bash
# Forcefully kills the 7-highlander process using SIGKILL (signal 9)
# shellcheck disable=SC2009

ps aux | grep "[7]-highlander" | awk '{print $2}' | while read -r pid; do
    kill -9 "$pid"
done
